version: '3.4'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-tracing
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "9411:9411"
      - "14268:14268"
      - "16686:16686"
  http-server-initiator:
    build:
      context: .
      dockerfile: src/http-server-initiator/Dockerfile
    ports:
      - 8080:8080
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - jaeger
  http-server-receiver:
    build:
      context: .
      dockerfile: src/http-server-receiver/Dockerfile
    ports:
      - 8081:8081
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - jaeger
      - http-server-initiator