version: '3.4'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-tracing
    ports:
      - 16686:16686
      - 6831:6831/udp
    environment:
      - JAEGER_AGENT_HOST=jaeger
    networks:
      - opentracing
  http-server-initiator:
    build:
      context: .
      dockerfile: src/http-server-initiator/Dockerfile
    ports:
      - 8080:8080
    environment:
      - HTTP_SERVER_HOSTNAME=0.0.0.0:8080
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - HTTP_SERVER_RECEIVER_HOSTNAME=http://http-server-receiver:8081
    depends_on:
      - jaeger
    networks:
      - opentracing
  http-server-receiver:
    build:
      context: .
      dockerfile: src/http-server-receiver/Dockerfile
    ports:
      - 8081:8081
    environment:
      - HTTP_SERVER_HOSTNAME=0.0.0.0:8081
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - jaeger
      - http-server-initiator
    networks:
      - opentracing

networks:
  opentracing: