version: '3.4'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-tracing
    ports:
      - 16686:16686
      - 6831:6831/udp
    environment:
      - JAEGER_AGENT_HOST=jaeger
    networks:
      - opentracing
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    networks:
      - opentracing
  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - AUTO_CREATE_TOPICS="true"
      - KAFKA_CREATE_TOPICS="todos:1:1"
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - opentracing
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=todos
      - POSTGRES_PASSWORD=todos
      - POSTGRES_USER=todos
    ports:
      - 5432:5432
    networks:
      - opentracing
  http-server-initiator:
    build:
      context: .
      dockerfile: src/http-server-initiator/Dockerfile
    ports:
      - 8080:8080
    environment:
      - HTTP_SERVER_HOSTNAME=0.0.0.0:8080
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - HTTP_SERVER_RECEIVER_HOSTNAME=http://http-server-receiver:8081
    depends_on:
      - jaeger
    networks:
      - opentracing
  http-server-receiver:
    build:
      context: .
      dockerfile: src/http-server-receiver/Dockerfile
    ports:
      - 8081:8081
    environment:
      - HTTP_SERVER_HOSTNAME=0.0.0.0:8081
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - GRPC_SERVER_HOSTNAME=grpc-server:50051
    depends_on:
      - jaeger
    networks:
      - opentracing
  grpc-server:
    build:
      context: .
      dockerfile: src/grpc-server/Dockerfile
    ports:
      - 50051:50051
    environment:
      - GRPC_SERVER_PORT=50051
      - KAFKA_TODO_TOPIC=todos
      - KAFKA_BROKER_ADDRESS=kafka:9092
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - jaeger
      - kafka
    networks:
      - opentracing
  kafka-consumer:
    build:
      context: .
      dockerfile: src/kafka-consumer/Dockerfile
    environment:
      - KAFKA_TODO_TOPIC=todos
      - KAFKA_BROKER_ADDRESS=kafka:9092
      - DATABASE_DSN=user=todos password=todos host=db port=5432 dbname=todos sslmode=disable pool_max_conns=10
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - jaeger
      - kafka
      - db
    networks:
      - opentracing

networks:
  opentracing: