@startuml

title Open Tracing Example

skinparam ParticipantPadding 10
skinparam BoxPadding 10

actor plinio

box "Services" #LightBlue
    participant "rest-service" as rest
    participant "grpc-service" as grpc
    participant "kafka-consumer" as consumer
end box

box "Open Tracing" #Orange
    participant "open-tracing" as ot
end box

box "Kafka" #LightYellow
    participant "kafka" as kafka
end box

box "Database"
    participant "database" as db
end box

plinio->rest: add a todo request
rest->ot: create trace
rest->grpc: add a todo request
grpc->ot: create sub-trace
grpc->kafka: publish message in todos topic forwarding tracing headers
rest<--grpc: ok
plinio<--rest: ok
kafka<--consumer: consume message and extract tracing headers and create sub-span
consumer->ot: create sub-trace
consumer->db: save todo
db->ot: create sub-trace
db<--consumer: ok
kafka<--consumer: commit offset

@enduml